<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'es'; // Idioma por defecto español
}

$userID = isset($_SESSION['id'])? (int)$_SESSION['id']: 0;

// if($userID<= 0){
//     header("Location: ../");
//     exit();
// }

function getCountrySelected($country)
{
    $country = strtoupper(trim((string) $country));
    $countries = [
        'AF' => 'Afganistán',
        'AL' => 'Albania',
        'DE' => 'Alemania',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguila',
        'AQ' => 'Antártida',
        'AG' => 'Antigua y Barbuda',
        'SA' => 'Arabia Saudita',
        'DZ' => 'Argelia',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaiyán',
        'BS' => 'Bahamas',
        'BH' => 'Baréin',
        'BD' => 'Bangladés',
        'BB' => 'Barbados',
        'BE' => 'Bélgica',
        'BZ' => 'Belice',
        'BJ' => 'Benín',
        'BM' => 'Bermudas',
        'BY' => 'Bielorrusia',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia y Herzegovina',
        'BW' => 'Botsuana',
        'BR' => 'Brasil',
        'BN' => 'Brunéi',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'BT' => 'Bután',
        'CV' => 'Cabo Verde',
        'KH' => 'Camboya',
        'CM' => 'Camerún',
        'CA' => 'Canadá',
        'QA' => 'Catar',
        'CL' => 'Chile',
        'CN' => 'China',
        'CY' => 'Chipre',
        'CO' => 'Colombia',
        'KM' => 'Comoras',
        'CG' => 'Congo',
        'CD' => 'Congo (Rep. Dem.)',
        'KP' => 'Corea del Norte',
        'KR' => 'Corea del Sur',
        'CR' => 'Costa Rica',
        'CI' => 'Costa de Marfil',
        'HR' => 'Croacia',
        'CU' => 'Cuba',
        'DK' => 'Dinamarca',
        'DM' => 'Dominica',
        'EC' => 'Ecuador',
        'EG' => 'Egipto',
        'SV' => 'El Salvador',
        'AE' => 'Emiratos Árabes Unidos',
        'ER' => 'Eritrea',
        'SK' => 'Eslovaquia',
        'SI' => 'Eslovenia',
        'ES' => 'España',
        'US' => 'Estados Unidos',
        'EE' => 'Estonia',
        'ET' => 'Etiopía',
        'PH' => 'Filipinas',
        'FI' => 'Finlandia',
        'FR' => 'Francia',
        'GA' => 'Gabón',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Grecia',
        'GD' => 'Granada',
        'GL' => 'Groenlandia',
        'GT' => 'Guatemala',
        'GN' => 'Guinea',
        'GQ' => 'Guinea Ecuatorial',
        'GW' => 'Guinea-Bisáu',
        'GY' => 'Guyana',
        'HT' => 'Haití',
        'HN' => 'Honduras',
        'HU' => 'Hungría',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Irán',
        'IQ' => 'Irak',
        'IE' => 'Irlanda',
        'IS' => 'Islandia',
        'IL' => 'Israel',
        'IT' => 'Italia',
        'JM' => 'Jamaica',
        'JP' => 'Japón',
        'JO' => 'Jordania',
        'KZ' => 'Kazajistán',
        'KE' => 'Kenia',
        'KG' => 'Kirguistán',
        'KI' => 'Kiribati',
        'KW' => 'Kuwait',
        'LA' => 'Laos',
        'LS' => 'Lesoto',
        'LV' => 'Letonia',
        'LB' => 'Líbano',
        'LR' => 'Liberia',
        'LY' => 'Libia',
        'LI' => 'Liechtenstein',
        'LT' => 'Lituania',
        'LU' => 'Luxemburgo',
        'MG' => 'Madagascar',
        'MY' => 'Malasia',
        'MW' => 'Malaui',
        'MV' => 'Maldivas',
        'ML' => 'Malí',
        'MT' => 'Malta',
        'MA' => 'Marruecos',
        'MU' => 'Mauricio',
        'MR' => 'Mauritania',
        'MX' => 'México',
        'FM' => 'Micronesia',
        'MD' => 'Moldavia',
        'MC' => 'Mónaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MZ' => 'Mozambique',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NI' => 'Nicaragua',
        'NE' => 'Níger',
        'NG' => 'Nigeria',
        'NO' => 'Noruega',
        'NZ' => 'Nueva Zelanda',
        'OM' => 'Omán',
        'NL' => 'Países Bajos',
        'PK' => 'Pakistán',
        'PW' => 'Palaos',
        'PA' => 'Panamá',
        'PG' => 'Papúa Nueva Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Perú',
        'PL' => 'Polonia',
        'PT' => 'Portugal',
        'GB' => 'Reino Unido',
        'CF' => 'República Centroafricana',
        'CZ' => 'República Checa',
        'DO' => 'República Dominicana',
        'RO' => 'Rumania',
        'RU' => 'Rusia',
        'RW' => 'Ruanda',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'Santo Tomé y Príncipe',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leona',
        'SG' => 'Singapur',
        'SY' => 'Siria',
        'SO' => 'Somalia',
        'ZA' => 'Sudáfrica',
        'SD' => 'Sudán',
        'SS' => 'Sudán del Sur',
        'SE' => 'Suecia',
        'CH' => 'Suiza',
        'SR' => 'Surinam',
        'TH' => 'Tailandia',
        'TZ' => 'Tanzania',
        'TJ' => 'Tayikistán',
        'TL' => 'Timor Oriental',
        'TG' => 'Togo',
        'TO' => 'Tonga',
        'TT' => 'Trinidad y Tobago',
        'TN' => 'Túnez',
        'TM' => 'Turkmenistán',
        'TR' => 'Turquía',
        'TV' => 'Tuvalu',
        'UA' => 'Ucrania',
        'UG' => 'Uganda',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistán',
        'VU' => 'Vanuatu',
        'VA' => 'Vaticano',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabue',
    ];

    $options = [];
    $defaultSelected = isset($countries[$country]) ? '' : ' selected';
    $options[] = '<option value="no-seleccionado"' . $defaultSelected . '>Selecciona un país</option>';

    foreach ($countries as $code => $label) {
        $selected = $code === $country ? ' selected' : '';
        $options[] = sprintf('<option value="%s"%s>%s</option>', $code, $selected, $label);
    }

    return implode(PHP_EOL, $options);
}

?>
